# Generated by Django 5.0.1 on 2024-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                (
                    "key_skills",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание вакансии"
                    ),
                ),
                (
                    "salary_min",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальный уровень зарплаты",
                    ),
                ),
                (
                    "salary_max",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальный уровень зарплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Валюта"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="Дата публикации вакансии"),
                ),
                (
                    "area_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Город"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансии",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
