# Generated by Django 5.0.1 on 2024-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "table_file_name",
                    models.CharField(
                        max_length=255, verbose_name="Путь к HTML файлу таблицы"
                    ),
                ),
                (
                    "image_path",
                    models.CharField(max_length=255, verbose_name="Путь к картинке"),
                ),
                ("analytics", models.TextField(verbose_name="Аналитика")),
            ],
        ),
    ]
