# Generated by Django 5.0.1 on 2024-01-19 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0002_trends"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trends",
            options={
                "verbose_name": "Аналитика востребованности",
                "verbose_name_plural": "Аналитика востребованности",
            },
        ),
    ]
