# Generated by Django 5.0.1 on 2024-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "table_file_name",
                    models.CharField(
                        max_length=255, verbose_name="Путь к HTML файлу таблицы"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="main/img/", verbose_name="Изображение"
                    ),
                ),
                ("analytics", models.TextField(verbose_name="Аналитика")),
            ],
            options={
                "verbose_name": "Аналитика востребованности",
                "verbose_name_plural": "Аналитика востребованности",
            },
        ),
    ]
