# Generated by Django 5.0.1 on 2024-01-19 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geography",
            options={
                "verbose_name": "Аналитика географии",
                "verbose_name_plural": "Аналитика географии",
            },
        ),
    ]
