# Generated by Django 5.0.1 on 2024-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSharpProgrammer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Оглавление")),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "responsibilities_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок описания профессии",
                    ),
                ),
                (
                    "responsibilities_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание профессии"
                    ),
                ),
                (
                    "requirements_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок требований",
                    ),
                ),
                (
                    "requirements_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Требования к профессии"
                    ),
                ),
                (
                    "development_prospects_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок перспектив",
                    ),
                ),
                (
                    "development_prospects_description",
                    models.TextField(blank=True, null=True, verbose_name="Перспективы"),
                ),
            ],
            options={
                "verbose_name": "Контент главной страницы",
                "verbose_name_plural": "Контент главной страницы",
            },
        ),
    ]
